language: c
compiler:
  - gcc
addons:
  apt:
    packages:
    - build-essential
    - pkg-config 
    - cmake 
    - libfreetype6-dev 
    - libogg-dev 
    - libtheora-dev 
    - libvorbis-dev
    - liballegro4-dev
    - libaldmb1-dev
script:
- mkdir build-liballegro
- cd build-liballegro
- cmake -D SHARED=off -DCMAKE_BUILD_TYPE=Debug ..
- make
